# Github Action workflow for CI test
name: CI-PKCS11-Tests

# trigger the workflow on specific event: manually, push and pull request
on:
  push:
    branches:
      - main
      - release-*
      - e2e_test_pkcs11
  pull_request:

# permission level for the workflow: set to read-all, which means read access to all repositories
permissions: read-all

# Defines an environment variable
env:
  GO_VERSION: '1.21'

# define the jobs to be executed as part of the workflow.
jobs:
  e2e-tests-pkcs11:
  # Job Name
    name: Run pkcs11 e2e tests
    # Run the Job on ubuntu-latest
    runs-on: ubuntu-latest
    # Define the series of steps to be executed in the job:
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      # Set up the Go environment with the specified Go version 
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Run pkcs11 end-to-end tests
        run: ./test/e2e_test_pkcs11.sh

